require("indent_blankline").setup({
	-- for example, context is off by default, use this to turn it on
	show_current_context = true,
	show_current_context_start = true,
	context_patterns = {
		"class",
		"return",
		"function",
		"method",
		"^if",
		"^while",
		"jsx_element",
		"^for",
		"^object",
		"^table",
		"block",
		"arguments",
		"if_statement",
		"else_clause",
		"jsx_element",
		"jsx_self_closing_element",
		"try_statement",
		"catch_clause",
		"import_statement",
		"operation_type",
		"^func",
		"while",
		"for",
		"with",
		"try",
		"except",
		"argument_list",
		"object",
		"dictionary",
		"element",
		"table",
		"tuple",
		"do_block",
	}, -- Patterns used to hightlight current context. See default ones here: https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/doc/indent_blankline.txt
})
